### ISSUE TITLE
Rhaboo adding value to arrays that don't belong to it. 

### ISSUE THREAD

**Issue by jwebcat** [adrianmay/rhaboo#18]
Great work on this man! 

I included it on my page with out init. 

I then noticed that it was adding a function to the end of an array being returned via messaging by a Web worker using lodash to compute uniques. 

I believe it was push: function

Thoughts?

**Comment by adrianmay** [comment]
Thanks!

I'm not sure what you mean here. Rhaboo does mess with the implementation of push and all the other mutating funtions of arrays. That's so that you can push etc to a persistent array and expect the change to persist. But it doesn't do that to *specific* arrays, rather, it replaces the version in the prototype. The new implelemtations behave just like the originals on non-persistent arrays. 

I'm not sure if that explains your issue. If you could post some code together with a description of what you think is going wrong then I could be more helpful.

Adrian.

**Comment by jwebcat** [comment]
Adrian, 

Thanks for the quick reply. 

I will post a screen shot of my console shortly I'm logging the array that is returned you can see the added function there.

**Comment by adrianmay** [comment]
Is this still alive or shall I close it?

**Comment by unematiii** [comment]
@jwebcat Do not iterate the arrays with for..in construct.
