### ISSUE TITLE
Support for using sessionStorage vs localStorage

### ISSUE THREAD

**Issue by ritter** [adrianmay/rhaboo#19]
Is there currently any support for using sessionStorage rather than localStorage?

**Comment by adrianmay** [comment]
I have no plans to do so because sessionStorage doesn't seem very useful. Rhaboo can forget things if you ask it to, so why choose an underlying storage that forgets things at times you can't control? 

If you really want it, you could search and replace through the minified script (I didn't try but I don't see why not.) Then everything would be in sessionStorage. Making rhaboo do both, e.g., creating an option to the constructor, would be an API complication that I find hard to justify.
