### ISSUE TITLE
Session storage

### ISSUE THREAD

**Issue by unematiii** [adrianmay/rhaboo#21]
Why not extend the interface to support Session storage in addition to Local storage. AFAIK, the API for both of the storage mechanisms is the same...

**Comment by adrianmay** [comment]
Hi Mati,

I think you're right that it would be easy. I guess the main constructor
would take a parameter for which storage to use.

It would be good for us both if you did it. Employers like to see
contributions to other peoples' repos cos it means that you're a team
player. For rhaboo it would be nice if it weren't just a one man show.

Interested? Just fork, write, and request a pull.

Adrian.

**Comment by ritter** [comment]
I've submitted a pull request with initial support for sessionStorage.  Feedback, changes, comments etc are welcome.

**Comment by ritter** [comment]
I had another thought, what about simply passing localStorage or sessionStorage in to the constructor?  I t would be easy to validate the object as an instance of Storage and then use.

**Comment by adrianmay** [comment]
Ah, Ritter. Sorry I slept on this for a few days. Thanks for the contribution! I'm on the road right now but perhaps I can look at this in the next few days. Passing either localStorage or sessionStorage sounds like a good idea to me. Please bear with me for a while. Adrian.

**Comment by adrianmay** [comment]
I can't imagine anybody wanting *everything* in sessionStorage - surely some things have to be remembered beyond the session. That means we need both storages side by side and a global variable specifying one or the other won't do.

Rhaboo already handles multiple references to the same object, so now it might be faced with a mixture of references from LS and SS. There's a danger of an object in LS referring to one in SS or vice versa. Both must be ruled out because SS objects disappear without notification, which would lead to a LS object pointing nowhere, or a refcount in LS being too high. Rather than slowing down the code with error checking, the developer can simply be warned. Cross references can still be achieved just by storing property names as strings.

So what's needed is that each persistent object needs to remember which type of storage it's in and pass that down to any non-persistent objects that are added to it. If any persistent objects are added to it then we either assume or check that the storage types match. I kinda like the word "perishable" for the SS constructor. I'll do this soon.

**Comment by adrianmay** [comment]
It's done. Use "perishable" instead of "persistent" to get an object in sessionStorage instead of localStorage. Don't mix references between the two storages or it'll just tear itself to pieces. There's a demo called cliches_session.html.

**Comment by unematiii** [comment]
@adrianmay Thank you so much of this! Having multiple storages was exactly what I needed.
